version: 2
jobs:
  install-dependancies:
    docker:
      - image: circleci/node:8.9.1-stretch-browsers
    # working_directory: ~/myfreestylejp
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-
      - run: yarn
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/node_modules
  build-production:
    docker:
      - image: circleci/node:8.9.1-stretch-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
            - yarn-
      - run: yarn build
  # test:
  #   docker:
  #     - image: circleci/node:8.9.1-stretch-browsers
  #   working_directory: ~/myfreestylejp
  #   steps:
  #     - checkout
  #     - run: echo "Testing..."
workflows:
  version: 2
  merge_feature_branch:
    jobs:
      - install-dependancies
      - build-production:
          requires:
            - install-dependancies
      # - test:
      #     requires:
      #       - build
      #     filter:
      #       branches:
      #         only:
      #           - /feature\/.*/
