version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1-stretch-browsers
    steps:
      - checkout
      - run: echo "hello world"
  test_feature_branch:
    steps:
      - checkout
      - run: echo "Testing..."
workflows:
  version: 2
  merge_feature_branch:
    jobs:
      - build
      - test_feature_branch:
          requires:
            - build
          filter:
            branches:
              only:
                - /feature\/.*/
